pipeline {
    agent any
    
    environment {
        DEVOPS_BATCH=AUG2022
    }
    parameters {
        choice(name: 'DEPLOYMENT_ENV',
        choices: ['UAT1', 'UAT2', 'PREPOD'],
        description : 'Select Env for Deploy'
        )
        string(name: 'Dummystr',
        description: 'Just a Dummy value',
        defaultValue: 'Akshay')
    }
    triggers { pollSCM('***')}

    option {
        buildDiscarder logRotator(artifacrDaysToKeepStr: ", artifactNumToKeepStr: ",daysToKeepStr: '2',numTokeepStr: '2'))
    }
    
    tools{
        jdk 'jdk11'
        maven 'maven'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }
    }

    post {
  always {
    slackSend channel: 'devops', message: 'BUILD COMPLETED'
  }
}
}