pipeline{
    agent any
    environment {
      JAVA_VERSION="11"
      DEVOPS_BATCH="AUG2022"
    }
    
    options {
      buildDiscarder logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '2', numToKeepStr: '2')
    }
    tools {
      jdk 'Jdk11'
      maven 'maven366'
    }

    stages {
      stage('checkout'){
        steps {
            checkout scm
        }
      }
      stage('compile'){
        steps {
            sh 'mvn compile'
        }
      }
     stage('test'){
        steps {
            sh 'mvn test'
        }
     }
    }
}
